apiVersion: v1
kind: Secret
metadata:
  name: {{ template "springadminserver.credentialsecret" . }}
  labels:
    {{- include "springadminserver.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.secret.credential.username | b64enc | quote }}
  password: {{ .Values.secret.credential.password | b64enc | quote }}