api:
  version: v1

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
  folder: ./logs

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8085}/eureka/

spring:
  application:
    name: 'usermanagement'
  datasource:
    url: jdbc:h2:mem:user
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
  boot:
    admin:
      client:
        enabled: false
        url: ${SPRING_ADMIN_SERVER_URL:http://localhost:8082}
        connect-timeout: 30000
        read-timeout: 30000
        instance:
          prefer-ip: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    metrics:
      enabled: true