api:
  version: v1

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
  folder: ./logs

# Swagger.ui url:
#http://localhost:8080/swagger-ui.html

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    probes:
      enabled: true
    livenessState:
      enabled: true
    readinessState:
      enabled: true

spring:
  datasource:
    url: jdbc:h2:mem:user
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2