apiVersion: v1
kind: Service
metadata:
  name: {{ include "eurekaserver.fullname" . }}
  labels:
    {{- include "eurekaserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.portui }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.portregister }}
      targetPort: http-register
      protocol: TCP
      name:  http-register
  selector:
    {{- include "eurekaserver.selectorLabels" . | nindent 4 }}
