server:
  port: 8082

spring:
  application:
    name: adminserver
  profiles:
    active: ${RUN_MODE:tst}
  boot:
    admin:
      client:
        api-path: /actuator

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
  client:
    registryFetchIntervalSeconds: 5
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8085}/eureka/

management:
  security:
    enabled: false

monitor:
  default-timeout: 60000
  status-interval: 15000
  status-lifetime: 15000
