server:
  port: 8082

spring:
  application:
    name: adminserver
  security:
    user:
      name: ${DEFAULT_USERNAME:admin}
      password: ${DEFAULT_PASSWORD:admin}
  boot:
    admin:
      client:
        api-path: /actuator

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
      user.name: ${DEFAULT_USERNAME:admin}
      user.password: ${DEFAULT_PASSWORD:admin}
  client:
    registryFetchIntervalSeconds: 5
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8085}/eureka/

management:
  security:
    enabled: false

monitor:
  default-timeout: 60000
  status-interval: 15000
  status-lifetime: 15000
